### ISSUE TITLE
Missing CREATE TABLE

### ISSUE THREAD

**Issue by PvdBerg1998** [jacobbudin/pinto#2]
Hello, I just found your project and it looks good for my usecase. I wondered if there is any specific reason there is no CREATE TABLE functionality?

**Comment by jacobbudin** [comment]
> I wondered if there is any specific reason there is no CREATE TABLE functionality?

@PvdBerg1998 No, there's no particular reason—just lack of interest. Right now, the library only covers data querying and manipulation. It excludes data definition (e.g., `CREATE TABLE`).

I'd accept a PR that added this functionality.

**Comment by PvdBerg1998** [comment]
Closing as I don't have time to implement this.
